#+STARTUP: latexpreview
#+LATEX_HEADER: \usepackage{bm}
#+LATEX_HEADER: \usepackage{svg}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \graphicspath{{pics/}}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

# Local Variables:
# org-ref-default-bibliography: refs.bib
# End:
#+TITLE: Higgs Boson classification
#+AUTHOR: Laurent Lejeune, Tatiana Fountoukidou, Guillaume de Montauzon
#+OPTIONS: toc:nil        no default TOC at all
 

*  Data pre-processing

** Data clean-up
About 70% of the samples contain missing values. Replacing missing values by the expectation over the valid samples leads to a distortion of the variable's distribution, which introduces a severe bias in regression procedures. A variant of K-Nearest-Neighbors strategy was implemented to fill-in missing values cite:malarvizhi12. To alleviate the computational cost, a random uniform sampling of the valid samples (samples without missing values) was performed prior to the nearest neighbors search.

** Data preparation
Computing the eigen-values of the covariance matrix reveals that the second highest eigen value is xxx% smaller than the highest.

* Method

** Adaboost with decision stumps
** Additive Logistic Regression cite:friedman98 

\bibliographystyle{ieeetr}
\bibliography{refs}
\printbibliography
