#+STARTUP: latexpreview
#+LATEX_HEADER: \usepackage{bm}
#+LATEX_HEADER: \usepackage{svg}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \graphicspath{{pics/}}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

# Local Variables:
# org-ref-default-bibliography: refs.bib
# reftex-default-bibliography: refs.bib
# End:
#+TITLE: Higgs Boson classification
#+SUBTITLE: Master's thesis proposal
#+AUTHOR: Laurent Lejeune
#+OPTIONS: toc:nil        no default TOC at all
 
#+BEGIN_LaTeX
\begin{figure}\centering
\subfloat[The Eye Tribe. Eye-gaze tracker.]{\label{fig:eyetribe} 
\includegraphics[width=0.3\textwidth]{pics/screenshot_2016-07-29_13-18-19.png}
} 
\subfloat[Example of a superpixel segmentation. The green circle indicates the location of the gaze.]{\label{fig:segmentation} 
\includegraphics[width=0.3\textwidth]{pics/screenshot_2016-07-27_15-16-43.png}
} 
\end{figure}
#+END_LaTeX

#+CAPTION: Min cost flow problem (example with 3 parts per instant). Beliefs are propagated to every parts in both time direction within a given time window. The flow travels from the source (S) towards the sink (T). 
#+ATTR_LaTeX: [h]{0.2\textwidth} :width 0.58\textwidth
#+LABEL: fig:minCost
[[file:pics/minCost.pdf]]

* Background
In order to train an efficient machine-learning-based classifier, the quantity/quality requirement on training data is of paramount importance for the performance of the final classification/segmentation framework (false/true positive rate, detection rate). Depending on the underlying classifier and domain of application, decent training sets typically amount to thousands of images. Furthermore, one usually relies on competent "experts" to generate and validate such training data.

In the medical practice, physicians often resort to quantitative and qualitative criterion computed on (sequences of) images to render a diagnosis. Machine learning methods have been extensively used in that frame, both for segmentation and classification cite:vijayakumar2007,gasmi2012,powell2008. However, knowledgeable experts are often scarce and overworked, which makes it difficult to obtain sufficient quantities of training data. This research project aims at replacing the traditional mouse labeling method with an eye-gaze tracker. That is, instead of labeling and delimiting the regions of interest by drawing on images with a computer mouse, the expert is asked to stare at the region of interest on sequences of images. An eye-gaze tracker is placed in front of the monitor and points towards the experts face. The device outputs the coordinates on the screen that the expert looked at. The class of the object of interest being known, the expert is asked to keep his eyes on the object while the sequence unfolds. We dub this approach _eye labeling_.

* Aim
 Mid-level segmentation techniques, such as superpixels cite:achanta2012,vandenbergh2014, are used to delimit objects or parts of objects that visually stand out relative to their neighbors. Such mid-level segmentation are applied to the whole sequence to be labeled.
We then leverage the appearance and location consistency of the object throughout the sequence in a belief propagation paradigm. The current solution consists in building a [[https://en.wikipedia.org/wiki/Directed_graph][directed graph]], taking "seen" regions (i.e. regions that contain the gaze-location) as root node. The graph is then expanded forward and backward in time. A min cost flow approach allows to select a set of paths such that the total cost (linear combination of edge weights) is minimized.

* Materials and Methods
The student will work on:
- Extending the existing belief network to take into account motion priors from eye-gaze coordinates.
- Investigate methodological and algorithmical solutions to reduce the computational cost of the linear programming formulation of the min cost flow problem.
- If time permits, [[https://en.wikipedia.org/wiki/Semi-supervised_learning][semi-supervised learning]] solutions will be applied to combine positive (examples labeled with a mouse) and pseudo labels (uncertain labels obtained with the belief network).
* Nature of the thesis
- Data analysis and interpretation: 0%
- Implementation: 60% 
- Litterature review: 10%
- Theory: 30%
* Requirements
The proposed masters thesis requires a theoretical background in computer-vision and machine learning. The practical skills include Python programming, along with Numpy and OpenCV (among others). Previous experience in MATLAB and/or C++/OpenCV will greatly help the transition to Python.
* Supervision
- PhD student: Laurent Lejeune
- Supervisor: Raphael Sznitman
* Institute
Ophtalmic Technology Lab, ARTORG Center, University of Bern.
* Contact 
Laurent Lejeune, laurent.lejeune@artorg.unibe.ch, Murtenstrasse 50, CH-3008 Bern, office C206.2. Tel: +41 31 632 76 11



\bibliographystyle{ieeetr}
\bibliography{../litteratureReview/refs}
\printbibliography
